### ISSUE TITLE
洛理新生前来支持!!

### ISSUE THREAD

**Issue by icepie** [vhxubo/lit-news#1]
最近也在学 `electron-app` , 正好看到咱学校的这个项目, 前来观望下!

**Comment by vhxubo** [comment]
:yum: 哈哈哈，以下是我使用&参考的项目：

- [electron-vue](https://github.com/SimulatedGREG/electron-vue)
- [electron-vue 系列教程](https://molunerfinn.com/tags/Electron-vue/)

希望可以帮到你。

**Comment by icepie** [comment]
nice! 
话说我在commit.path看到你的qq邮箱了, 我能加你好友么
共勉!
